management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8084
spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testDB
    password: sa
    username: sa